# Generated by Django 3.1.6 on 2021-02-14 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_events_subscriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'Varieties'},
        ),
    ]
