# Generated by Django 3.1.6 on 2021-02-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210216_0738'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Wine',
        ),
    ]
