# Generated by Django 3.1.6 on 2021-02-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210222_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
