# Generated by Django 3.1.6 on 2021-03-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('winery', models.CharField(blank=True, max_length=254, null=True)),
                ('vintage', models.IntegerField(blank=True, null=True)),
                ('alc_vol', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pairing', models.CharField(blank=True, max_length=254, null=True)),
                ('is_a_subscription', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('region', models.ForeignKey(blank=True, max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.wine_region')),
                ('variety', models.ForeignKey(blank=True, max_length=254, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.variety')),
            ],
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
    ]
